### PR TITLE
Added the ability to set a default scene

### PR DESCRIPTION
**Pull request by MarcJenningsUK**
Totally non-production ready code, but this adds the ability to define a default scene the notes of in any page with the syntax 'OBSDEF:MySceneName'
If set multiple times it can allow the default to be changed mid-presentation.

### CODE REVIEW

**Comment by MarcJenningsUK** [comment]
Added basic error checking for available scenes in OBS to try to eliminate exceptions if you mistype a scene name.

**Comment by shanselman** [comment]
Nice! Can you take a look at the current head and consider its new functionality (find the FIRST instance of the OBS: prefix) and rebase on that?

**Comment by MarcJenningsUK** [comment]
Wow, I'm exposing my git ignorance to myself on this, but I got there.  There's a change I needed to add that will ignore all but the first instance of the OBS: tag in case there are multiple ones in a slide.  That still lets me look through other lines for the default scene definition.

**Comment by MarcJenningsUK** [comment]
So this adds the ability to have a default scene, ignores multiple scene change notes, handles errors gracefully and a few small tweaks.

**Comment by bparks** [comment]
I really like this concept. One question, though: what happens if a default scene is never specified and a particular slide doesn't list its own scene (i.e. it would fall back to an undefined default)?

**Comment by shanselman** [comment]
@bparks good question, or just not move?

**Comment by MarcJenningsUK** [comment]
If no default is set, and no scene change is specified in a slide, the scene will stay where it was last set.  The idea was that a default view (maybe a talking head in the corner) would only need to be overridden on specific slides, and if the slide get reordered there is no need to remember to call your default.

**Comment by MarcJenningsUK** [comment]
This should be ready to quickly merge @shanselman

**Comment by shanselman** [comment]
@MarcJenningsUK cool...I checked it (maybe I was late because of Ignite) and it's got conflicts. I will look later this week.

**Comment by MarcJenningsUK** [comment]
Closing the request as the baseline got away from me.  I'll open another based on the current codebase.  I suck at GitHub.

**Pull request closed without merging**
